### PR TITLE
feat: Add support for generating completions for Amazon CloudWhisperer CLI

### PR DESCRIPTION
**Pull request by miguelmig**
Related to #2804
This PR still has a bit of naming confusion between `Amazon Q`, `Amazon Code Whisperer CLI` and even `Fig` so I'm looking for some guidance on how to keep the naming in the code. 
It's my first attempt at contributing and my first try at Rust as well so feel free to criticize 

This still misses the automated publish step as I'm waiting for feedback before moving forward with that

### CODE REVIEW

**Comment by jdx** [comment]
I would accept this as an extension to usage but not into mise directly

**Comment by miguelmig** [comment]
@jdx Could you give some more context? Usage appears to have its own spec format, and Amazon Cloud Whisperer CLI has a different spec format for completions

**Comment by jdx** [comment]
Usage could output fig completions like it does for bash/zsh/fish.

**Comment by jdx** [comment]
Simple clap completions like this would be incomplete, missing things like completing tool names/versions

**Pull request closed without merging**
