### PR TITLE
fix(shell/zsh.rs): typo in shell alias name

### PR DESCRIPTION
**Pull request by powerman**

### CODE REVIEW

**Comment by powerman** [comment]
Sorry, I'm not a rust dev, so I'm not familiar with it workflow to update golden (snapshot) tests, thus I'll leave updating tests to you.

**Review by roele — COMMENTED** [review]
seems the alias changed at some point and other shell implementations such as `bash`, `fish` and `nushell` are also affected.

**Review by roele — COMMENTED** [review]
fixed other shells and snapshots in #2901 which replaces this PR

**Comment by powerman** [comment]
Great, thanks! Closing this one.

**Pull request closed without merging**
