### PR TITLE
docs: better warning when venv auto create is skipped

### PR DESCRIPTION
**Pull request by syhol**
```console
mise is 📦 v2024.12.10 via 🥟 v1.1.38 via  v23.3.0 via 🐍 v3.13.0 (.venv) via 🦀 v1.83.0 
❯ rm -rf .venv
mise WARN  no venv found at: ~/Code/syhol/mise/.venv

mise will automatically create the venv once all requested python versions are installed.
To install the missing python versions and create the venv, please run:
mise install

mise is 📦 v2024.12.10 via 🥟 v1.1.38 via  v23.3.0 via 🐍 v3.13.0 (.venv) via 🦀 v1.83.0 
❯ vim mise.toml # <-- changing env._.python.venv.create from true to false
mise WARN  no venv found at: ~/Code/syhol/mise/.venv

To create a virtualenv manually, run:
python -m venv ~/Code/syhol/mise/.venv
mise WARN  missing: python@3.9.21
```

### CODE REVIEW

**Comment by jdx** [comment]
So showing warnings for literally anything inside of `hook-env` I've found to be almost always a bad idea. If for some reason you don't want this to be displayed, you'll be annoyed with it constantly. I think we should keep this as debug level. If we _were_ to do it, it would certainly have to fit on a single line.

For example, I recently removed warnings for similar situations with `_.source` and `_.file` so mise just silently ignores their non-existence.

**Comment by jdx** [comment]
I think the better thing to do here is put the information into `mise dr`

**Comment by syhol** [comment]
I'm not actually adding a new warning here, just changing the existing warning if it's create = true. Sorry I should have included more context in my description.

It comes from this ticket: https://github.com/jdx/mise/issues/1898#issue-2241448074

If you still want to close this PR, that's no problem.

**Comment by jdx** [comment]
oh I see, I saw the debug! and assumed you were increasing the visibility, it's probably fine. If people complain, we can always tweak it.

**Pull request merged**
