### PR TITLE
docs: Update index page

### PR DESCRIPTION
**Pull request by hverlin**
Just an idea of things which could be added on the home page to get a super quick idea of what `mise` can do.
This is all in Markdown, but it could be possible to build something a bit prettier, more like on the https://vite.dev homepage (obviously not as advanced, but for example, presenting some information into two columns would help)

### CODE REVIEW

**Comment by hverlin** [comment]
Maybe something like this could work well:

image

**Comment by hverlin** [comment]
@jdx Would you be interested in having something like in the screenshot?

**Comment by jdx** [comment]
yeah I think that's excellent, the landing page is definitely too spartan at the moment

**Comment by hverlin** [comment]
will re-open another later

**Pull request closed without merging**
