### PR TITLE
docs: show information about github rate limits when erroring due to 403

### LINKED ISSUE #2428: With Ubi backend i got HTTP status client error forbidden
**Describe the bug**
Here my config

config.toml
```toml
[tools]
"cargo:ripgrep" = "14.1.0"
"cargo:ripgrep_all" = "0.10.6"
"cargo:starship" = "1.20.1"
"cargo:eza" = "0.18.23"
"cargo:fd-find" = "10.1.0"
"cargo:cargo-make" = "0.37.15"
"cargo:ubi" = "0.1.1"
"ubi:muesli/duf" = "v0.8.1"
# borg = "1.3.4"
# velero = "1.11.1"
argocd = "2.7.6"
awscli = "2.13.8"
bitwarden = "2023.7.0"
buildpack = "0.28.0"
choose = "latest"
cmctl = "1.12.2"
crane = "0.16.1"
flux2 = "2.0.1"
fluxctl = "1.25.4"
fzf = "0.42.0"
github-cli = "2.32.1"
glab = "1.31.0"
helm = "3.12.1"
jq = "1.6"
jx = "3.10.95"
k3d = "5.5.2"
k9s = "latest"
krew = "0.4.4"
kubectl = "1.27.3"
kubectx = "0.9.4"
kubetail = "latest"
kustomize = "5.1.0"
mc = "2023-08-08T17-23-59Z"
mkcert = "1.4.4"
node = "latest"
nodejs = "20.5.0"
packer = "1.9.1"
pnpm = "8.6.10"
rust-analyzer = "latest"
stern = "1.25.0"
weave-gitops = "0.29.0"
yq = "4.34.1"


[settings]
experimental = true

```

**To Reproduce**
Use my config and try to do mise install

**Expected behavior**
Works 

**`mise doctor` output**

```text
  19:38  mise doctor                                                                                                                                                                        
version: 2024.8.4 linux-x64 (8d2aed1 2024-08-02)
activated: yes
shims_on_path: no

build_info: 
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Fri, 2 Aug 2024 13:30:49 +0000
  Rust Version: rustc 1.80.0 (051478957 2024-07-21)
  Profile: release

shell: 
  /bin/fish
  fish, version 3.7.0

dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files: 
  ~/.config/mise/config.toml
  ~/.mise.toml

backends: 
  cargo
  core
  go
  npm
  pipx
  spm
  ubi

plugins: 
  argocd         https://github.com/beardix/asdf-argocd.git#429bbf9
  awscli         https://github.com/MetricMike/asdf-awscli.git#ac99537
  bitwarden      https://github.com/vixus0/asdf-bitwarden.git#c3679ff
  borg           https://github.com/lwiechec/asdf-borg#0922c60
  buildpack      https://github.com/johnlayton/asdf-buildpack.git#4301773
  bun            (core)
  cargo-make     https://github.com/kachick/asdf-cargo-make.git#6d323bd
  choose         https://github.com/carbonteq/asdf-choose.git#0291009
  cmctl          https://github.com/asdf-community/asdf-cmctl.git#26740f9
  crane          https://github.com/dmpe/asdf-crane#dc3b71a
  deno           (core)
  dotnet         https://github.com/hensou/asdf-dotnet#832dcd5
  duf            https://github.com/NeoHsu/asdf-duf.git#61e14e2
  erlang         (core)
  exa            https://github.com/nyrst/asdf-exa.git#3f525b7
  eza            https://github.com/lwiechec/asdf-eza.git#eee3d59
  fd             https://gitlab.com/wt0f/asdf-fd.git#17d56e0
  flux2          https://github.com/tablexi/asdf-flux2.git#771755e
  fluxctl        https://github.com/stefansedich/asdf-fluxctl.git#c2ecce0
  fzf            https://github.com/kompiro/asdf-fzf.git#d19eb67
  github-cli     https://github.com/bartlomiejdanek/asdf-github-cli.git#e0605b7
  glab           https://github.com/particledecay/asdf-glab.git#2c081ae
  go             (core)
  helm           https://github.com/Antiarchitect/asdf-helm.git#f4b7f38
  java           (core)
  jq             https://github.com/lsanwick/asdf-jq.git#addae51
  jx             https://github.com/vbehar/asdf-jx.git#8a1a055
  k3d            https://github.com/spencergilbert/asdf-k3d.git#5b0e5b9
  k9s            https://github.com/looztra/asdf-k9s.git#2b3af87
  krew           https://github.com/bjw-s/asdf-krew.git#eea6046
  kubectl        https://github.com/asdf-community/asdf-kubectl.git#cbe6df4
  kubectx        https://gitlab.com/wt0f/asdf-kubectx.git#8c0b4aa
  kubetail       https://github.com/janpieper/asdf-kubetail.git#57d25ad
  kustomize      https://github.com/Banno/asdf-kustomize.git#8e929af
  mc             https://github.com/penpyt/asdf-mc.git#b0458cf
  mkcert         https://github.com/salasrod/asdf-mkcert.git#e706f46
  node           (core)
  packer         https://github.com/asdf-community/asdf-hashicorp.git#f1602b6
  php            https://github.com/asdf-community/asdf-php.git#1eaf4de
  pnpm           https://github.com/jonathanmorley/asdf-pnpm.git#305baff
  postgres       https://github.com/smashedtoatoms/asdf-postgres.git#acbbc49
  python         (core)
  ripgrep        https://gitlab.com/wt0f/asdf-ripgrep.git#e836665
  ruby           (core)
  rust-analyzer  https://github.com/Xyven1/asdf-rust-analyzer#301bc6a
  stern          https://github.com/looztra/asdf-stern.git#e17efba
  tealdeer       https://github.com/emersonmx/asdf-tealdeer.git#9b76995
  weave-gitops   https://github.com/deas/asdf-weave-gitops#296cdb4
  yq             https://github.com/sudermanjr/asdf-yq.git#772992f
  zig            (core)
mise failed to resolve toolset: Failed to resolve ubi:muesli/duf@v0.8.1 from ~/.config/mise/config.toml: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/muesli/duf/releases): error resolving versions

toolset: 
  cargo:ripgrep@14.1.0  
  cargo:ripgrep_all@0.10.6  
  cargo:starship@1.20.1  
  cargo:eza@0.18.23     (missing)
  cargo:fd-find@10.1.0  (missing)
  cargo:cargo-make@0.37.15  (missing)
  cargo:ubi@0.1.1       (missing)
  argocd@2.7.6          
  awscli@2.13.8         
  bitwarden@2023.7.0    
  buildpack@0.28.0      
  choose@1.3.4          
  cmctl@1.12.2          
  crane@0.16.1          
  flux2@2.0.1           
  fluxctl@1.25.4        
  fzf@0.42.0            
  github-cli@2.32.1     
  glab@1.31.0           
  helm@3.12.1           
  jq@1.6                
  jx@3.10.95            
  k3d@5.5.2             
  k9s@0.32.5            
  krew@0.4.4            
  kubectl@1.27.3        
  kubectx@0.9.4         
  kubetail@1.6.20       
  kustomize@5.1.0       
  mc@2023-08-08T17-23-59Z  
  mkcert@1.4.4          
  node@20.5.0           
  packer@1.9.1          
  pnpm@8.6.10           
  rust-analyzer@2024-07-29  
  stern@1.25.0          
  weave-gitops@0.29.0   
  yq@4.34.1             

env_vars: 
  MISE_SHELL=fish

settings: 
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = true
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "/var/home/yodatak/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
2 problems found:

1. shims are missing, run mise reshim to create them
   Missing shims: starship

2. unused shims are present, run mise reshim to remove them
   Unused shims: kubectl-krew

```

```
  19:40  mise reshim                                                                                                                                                                        
mise failed to resolve toolset: Failed to resolve ubi:muesli/duf@v0.8.1 from ~/.config/mise/config.toml: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/muesli/duf/releases): error resolving versions

  19:38  RUST_BACKTRACE=full mise install                                                                                                                                                   
Error: 
   0: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/muesli/duf/releases)

Location:
   src/http.rs:61

Version:
   2024.8.4 linux-x64 (8d2aed1 2024-08-02)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮                               
   3: mise::http::Client::get::{{closure}}::{{closure}}::{{closure}}::h434e97dc53add92f.22237<unknown>
      at <unknown source file>:<unknown line>
   4: mise::http::Client::get::{{closure}}::h336468f81c4ab9ef.22215<unknown>
      at <unknown source file>:<unknown line>
   5: <core::pin::Pin<P> as core::future::future::Future>::poll::h45c44884e63416b9
      at <unknown source file>:<unknown line>
   6: mise::github::list_releases::hdecaad5bcefdbca2
      at <unknown source file>:<unknown line>
   7: once_cell::imp::OnceCell<T>::initialize::{{closure}}::hc5f4b987241b7170
      at <unknown source file>:<unknown line>
   8: once_cell::imp::initialize_or_wait::hd3610dd45a997824
      at <unknown source file>:<unknown line>
   9: once_cell::imp::OnceCell<T>::initialize::h98cb0302dcdf60b0
      at <unknown source file>:<unknown line>
  10: <mise::backend::ubi::UbiBackend as mise::backend::Backend>::_list_remote_versions::h7fb6935cdc6419ef
      at <unknown source file>:<unknown line>
  11: mise::backend::Backend::list_versions_matching::h352a0e78fa69fd0e
      at <unknown source file>:<unknown line>
  12: mise::toolset::tool_version::ToolVersion::resolve_version::h907de87eda7cc8f1
      at <unknown source file>:<unknown line>
  13: mise::toolset::tool_version::ToolVersion::resolve::h0e4133d54bf94c7d
      at <unknown source file>:<unknown line>
  14: std::sys_common::backtrace::__rust_begin_short_backtrace::hba0dfc893cbbff01
      at <unknown source file>:<unknown line>
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}::h0aee04d348c64d1c
      at <unknown source file>:<unknown line>
  16: std::sys::pal::unix::thread::Thread::new::thread_start::h3b8e81128811868f
      at <unknown source file>:<unknown line>
  17: start_thread<unknown>
      at <unknown source file>:<unknown line>
  18: __GI___clone3<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

```

### PR DESCRIPTION
**Pull request by jdx**
Fixes #2428

### CODE REVIEW

**Comment by powerman** [comment]
I've just hit this issue because token I've set years ago in my shell config is expired.
Probably it makes sense to mention this possible reason in error message/docs in case token is set.

**Comment by jdx** [comment]
I don't want to make assumptions about HTTP error codes. 403 is an exception because it will be extremely common.

**Comment by powerman** [comment]
You think 403 is somehow differ from 401? :smile: 

```sh
$ GITHUB_API_TOKEN=bad mise use usage@0.12.0
mise ERROR Failed to install usage@0.12.0
mise ERROR Failed to install with ubi 'ubi:jdx/usage@0.12.0': HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/jdx/usage/releases/tags/v0.12.0)
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

**Comment by jdx** [comment]
401 means they already set GITHUB_TOKEN at one point so they should be able to figure it out

**Pull request merged**
