### PR TITLE
feat(pipx): add support for specifying package extras

### LINKED ISSUE #2491: pipx: support features
pipx has a concept of optional features upon package installation, via `pipx install package[feature,…]`.  This is used, for example, by [Harlequin](https://harlequin.sh/docs/getting-started).

To my knowledge, mise has no support for this.  Would it be possible to add it?

As a work-around, for the example of Harlequin, one can install things via `pip install harlequin parlequin-postgress` etc. instead.

### PR DESCRIPTION
**Pull request by antoniomdk**
Closes #2491

Some Python tools support optional features upon package installation, via `pipx install package[feature,…]`. This is used, for example, by [Harlequin](https://harlequin.sh/docs/getting-started).

This PR adds support for specifying extras via

```toml
mytool = { version = '3.10', extras = 'foo,bar' }
```

NOTE: It only works for tools published to a registry (e.g PyPI), git-based tools require a different syntax than the one already implemented. (`git+...#egg=project[...]`).

NOTE: I had some issues setting up the local docker environment (unrelated to this project), so I couldn't run the e2e tests. There may be other parts of the code that could complain if using `[, ]` in the tool name, but the PyPI resolution error is the first one that popped up when trying to use package extras.

### CODE REVIEW

**Comment by jdx** [comment]
I think Tool Options would be a better solution as it wouldn't require inventing a new convention https://mise.jdx.dev/dev-tools/#tool-options

**Comment by antoniomdk** [comment]
@jdx How would you propose the syntax for tool options in this case? Python extras are a list rather than a map, maybe something like 
```
mytool = { version = '3.10', extras = ['bar'] }
```

**Comment by jdx** [comment]
I think for now unfortunately it only supports strings so you will need to do this:

```toml
mytool = { version = '3.10', extras = 'foo,bar' }
```

**Comment by antoniomdk** [comment]
That's fine, I'll update the PR to accommodate the tool options convention!

**Comment by antoniomdk** [comment]
@jdx I've updated the code to use `ToolVersions`. Not sure if we have a way to add validation for the extra field, but probably the pipx/uvx error will be informative enough.

**Comment by jdx** [comment]
you've got a test fialure

**Comment by antoniomdk** [comment]
@jdx this is ready for review. The git history is kind of messy, let me know if you want me to clean it up before merging 👍

**Pull request merged**
