### PR TITLE
feat: Add many tools to ubi backend fzf, cmtl, ripgrep-all ( rga), go…

### PR DESCRIPTION
**Pull request by yodatak**
…ldwarden, borg

fzf, cmtl, ripgrep-all ( rga), goldwarden, borg

Hello i don't remove old asdf i don't know if we shoud keep them or not so i add like this

### CODE REVIEW

**Comment by jdx** [comment]
does ripgrep work in ubi?

> Hello i don't remove old asdf i don't know if we shoud keep them or not so i add like this

we should keep them, it'll be used if people want to disable ubi for whatever reason

**Comment by yodatak** [comment]
I add ripgrep as it work with ubi ! @jdx

**Comment by jdx** [comment]
did you test borg and ripgrep? they don't seem to work for me:

```
m x borg -- which borg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.41s
     Running `target/debug/mise x borg -- which borg`
Error: 
   0: Failed to install borg@changelog-1.2.5
   1: Failed to install with ubi 'ubi:borgbackup/borg@changelog-1.2.5': HTTP status client error (404 Not Found) for url (https://api.github.com/repos/borgbackup/borg/releases/tags/vchangelog-1.2.5)

Location:
   src/backend/ubi.rs:113

Version:
   2024.10.10-DEBUG macos-arm64 (1f8f59f 2024-10-26)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by yodatak** [comment]
It failed to me also borg but ripgrep work i close the pr to make smaller one and be sure it work ( my platform is linux it would be nice to have a pr CI to test mac and linux

**Pull request closed without merging**
