### PR TITLE
feat: add argc plugin to registry

### PR DESCRIPTION
**Pull request by rgeraskin**
Adds an asdf plugin for Argc, an open-source Bash CLI framework: https://github.com/sigoden/argc

Also PR'd to asdf-plugins: https://github.com/asdf-vm/asdf-plugins/pull/1061

### CODE REVIEW

**Comment by jdx** [comment]
Does it work with ubi?

**Comment by roman-geraskin-m10** [comment]
yes, it works with ubi. But to use it with ubi I have to add extra tools to install ubi itself
```
[tools]
rust = "1.82.0"
ubi = "0.1.2"
"ubi:sigoden/argc" = "v1.20"
```

Also, I can just use rust to install argc without ubi
```
[tools]
rust = "1.82"
"cargo:argc" = "v1.20"
```

But I think a much simpler way to install argc is to use asdf backend
```
[tools]
argc = "1.20"
[plugins]
argc = "https://github.com/rgeraskin/asdf-argc"
```

This PR is aimed to drop the need of `[plugins]` section in `.mise.toml`

**Comment by jdx** [comment]
ubi is built into mise itself so it does not need to be separately installed

**Comment by roman-geraskin-m10** [comment]
thanks, I've used an outdated mise. Works great with ubi!

**Comment by jdx** [comment]
You can still add it to the registry with ubi

**Pull request closed without merging**
