### PR TITLE
refactor(registry): use aqua for more tools

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by jdx** [comment]
seems a lot of these don't work

**Comment by scop** [comment]
> seems a lot of these don't work

I tested all of them to work, but I see some test adjustments were needed, thanks for taking care of those.

I did not find documentation how to run the registry tests myself and I'm not having luck with trying out https://mise.jdx.dev/contributing.html#dev-container, so I'm skipping tests for my registry modifications for now (trying to add ones blindfolded though).

---

Maybe it deserves a separate issue of its own, but the errors I see are like
```shellsession
$ mise trust
mise trusted ...
mise ERROR [.../mise.toml] npm:prettier@3: No such file or directory (os error 2)
mise ERROR [.../mise.toml] npm:markdownlint-cli@latest: No such file or directory (os error 2)
mise ERROR error resolving versions
# maybe because I don't have node/npm installed? the contributing page doesn't mention needing them
```
...and for example
```shellsession
$ mise run docker:cargo build
mise WARN  failed to resolve toolset: [.../mise.toml] npm:prettier@3: No such file or directory (os error 2)
mise Installed binary into /home/scop/.local/share/mise/installs/actionlint/1.7.4/bin/actionlint
mise Installed binary into /home/scop/.local/share/mise/installs/wait-for-gh-rate-limit/0.1.8/bin/wait-for-gh-rate-limit
mise Installed binary into /home/scop/.local/share/mise/installs/slsa-verifier/2.6.0/bin/slsa-verifier
mise slsa-verifier@2.6.0 ✓ installed
mise actionlint@1.7.4  ✓ installed
mise wait-for-gh-rate-limit@0.1.8 ✓ installed
mise bun@1.1.38        ✓ installed
mise cosign@2.4.1      ✓ installed
mise pipx:toml-sort@0.24.2 install
mise cargo-binstall@1.10.15 ✓ installed
mise pre-commit@4.0.1  ✓ installed
mise jq@1.7.1          ✓ installed
mise ripgrep@14.1.1    ✓ installed
mise ERROR failed to install pipx:toml-sort@0.24.2
mise ERROR failed to execute command: pipx install toml-sort==0.24.2
mise ERROR No such file or directory (os error 2)
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
mise WARN  error deserializing __MISE_SESSION: missing field `env`
# maybe because I don't have pipx installed?
```

**Comment by jdx** [comment]
you just run `mise test-tool`

**Comment by jdx** [comment]
I wouldn't bother with the docker setup, I marked those tasks as hidden since they're not working. I don't use that setup.

**Pull request merged**
