### PR TITLE
refactor: use aqua for nfpm

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by jdx** [comment]
doesn't seem this one works:

```
mise  main ❯ m x aqua:nfpm -- nfpm --version
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.45s
     Running `target/debug/mise x 'aqua:nfpm' -- nfpm --version`
mise WARN  invalid aqua tool: nfpm
mise WARN  failed to resolve toolset: [--runtime] aqua:nfpm@latest: HTTP status client error (404 Not Found) for url (https://mise-versions.jdx.dev/aqua-registry/nfpm/registry.yaml)
Error: 
   0: "nfpm" couldn't exec process: No such file or directory

Location:
   src/cli/exec.rs:97

Version:
   2024.11.31-DEBUG macos-arm64 (675a2b0 2024-11-27)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

you can add a test for these by doing this:

```toml
nfpm.backends = [...]
nfpm.test = ['nfpm --version', 'nfpm version {{version}}']
```

**Comment by jdx** [comment]
oh I just fat fingered it

**Comment by jdx** [comment]
I added a test for this one, you can run these with `mise test-tool nfpm`

**Comment by scop** [comment]
> I added a test for this one, you can run these with `mise test-tool nfpm`

Thanks for the info :+1:

**Pull request merged**
